spring.application.name=buspass
server.port=8090

# =========================================================
# MySQL Database Configuration
# =========================================================
spring.datasource.url=jdbc:mysql://localhost:3306/buspass_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=root26
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================================================
# JPA / Hibernate Configuration
# =========================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# =========================================================
# API
# =========================================================
spring.jackson.serialization.write-dates-as-timestamps=false